spring:
  profiles:
    active:
    - developement

---
server:
  port: 8181
spring:
  profiles: developement
  datasource:
    url: jdbc:mysql://localhost:3306/mydatabase?useSSL=false
    username: root
    password: masterkey
    initialize: true
  data:
    rest:
      base-path: /v1/api
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

---
spring:
  profiles: production
  datasource:
    username: root
    password: masterkey
    url: jdbc:mysql://mysql:3306/mydatabase
  data:
    rest:
      base-path: /v1/api
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
---
spring:
  profiles: unittester
  jpa:
    database: H2
    show-sql: true
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE