spring:
  profiles:
    active:
    - production

---
spring:
  profiles: developement
  datasource:
    url: jdbc:mysql://localhost:3306/mydatabase?useSSL=false
    username: root
    password: masterkey
    initialize: false
  data:
    rest:
      base-path: /v1/api
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
---
spring:
  profiles: preproduction
  datasource:
    username: root
    password: masterkey
    url: jdbc:mysql://192.168.99.100:3306/mydatabase?useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.jdbc.Driver
    initialize: true
    
  data:
    rest:
      base-path: /v1/api
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

---
spring:
  profiles: production
  datasource:
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
    url: jdbc:mysql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
    driver-class-name: com.mysql.jdbc.Driver
    initialize: true
    
  data:
    rest:
      base-path: /v1/api
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
---
spring:
  profiles: unittester
  jpa:
    database: H2
    show-sql: true
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE